stages:
  report:
    cmd: bash -c "cd report && latexmk article.tex -pdf"
    outs:
      - report/article.pdf
    deps:
      - report/article.tex
      - report/structure.tex
  sem_eval_data:
    cmd: python3 code/build_sem_eval_data.py --csv_path data/sem_eval_data.csv
    outs:
      - data/sem_eval_data.csv
    deps:
      - code/build_sem_eval_data.py
      - data/multilingual-all-words.en.xml
      - data/wordnet.en.key
  seed_set_data:
    cmd: python3 code/build_seed_set.py --csv_path data/seed_set_data.csv
    outs:
      - data/seed_set_data.csv
    deps:
      - code/build_seed_set.py
  train_logistic_model:
    cmd: python code/train_logistic_model.py --data_path data/seed_set_data.csv --model_path data/logistic.joblib
    outs:
      - data/logistic.joblib
    deps:
      - code/train_logistic_model.py
      - data/seed_set_data.csv