params:
  - model
stages:
  download_models:
    foreach: ${model}
    do:
      cmd: bash src/download.sh models ${key}
      outs:
        - models/${key}
  report:
    cmd: bash -c "cd report && latexmk article.tex -pdf"
    outs:
      - report/article.pdf

