################# Header ################
Bootstrap: docker
From: texlive/texlive:latest-full-doc

%environment
    SHELL=/bin/bash
    PYTHON_VERSION=3
    PATH="/opt/local/bin:${PATH}"
    PYTHONPATH="/opt/llama:/opt/local/bin/:${PYTHONPATH}"
    export SHELL PYTHON_VERSION PATH PYTHONPATH

%files
    requirements.txt requirements.txt
    ./submodules/llama /opt/llama

################# Post Section ################
%post
    echo "Setting environment variables"
    export DEBIAN_FRONTEND=noninteractive

    # Install apt packages
    apt-get update
    apt-get install -y curl software-properties-common build-essential rsync python3-launchpadlib
    add-apt-repository ppa:deadsnakes/ppa -y
    apt-get update

    # Installing LaTeX packages...
    tlmgr init-usertree && \
    tlmgr update --all
    tlmgr install koma-script

    # Install specific Python version
    PYTHON_VERSION=3
    echo "Install python${PYTHON_VERSION}.."
    apt-get install -y python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-distutils python3-venv

    /usr/bin/python${PYTHON_VERSION} -m venv /opt/local

    echo "Installing pip.."
    curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    /opt/local/bin/python3 get-pip.py

    /opt/local/bin/pip3 install --upgrade pip

    # Make the newly installed pip the default
    update-alternatives --install /usr/local/bin/pip pip /opt/local/bin/pip${PYTHON_VERSION} 1
    update-alternatives --install /usr/local/bin/pip3 pip3 /opt/local/bin/pip${PYTHON_VERSION} 1

    echo "Installing python requirements"
    pip3 install -r requirements.txt

    echo "Install llama submodule"
    pip3 install -e /opt/llama

    echo "Install NLTK data"
    /opt/local/bin/python3 -m nltk.downloader -d /opt/local/share/nltk_data all

    # Clean apt cache to reduce image size
    apt-get clean
